---
title: Case Study 10
author: Emily McCray
date: November 5th, 2024
output: github_document
---

#installing new libraries
#install.packages("ncdf4")
#install.packages("rasterVis")
#install.packages("ggmap")
#install.packages("ggplot2")
#install.packages("terra")
 
#load in libraries 
library(terra)
library(rasterVis)
library(ggmap)
library(knitr)
library(sf)
library(ncdf4)
library(dplyr)
library(ggplot2)

dir.create("data",showWarnings = F) #create a folder to hold the data

lulc_url="https://github.com/adammwilson/DataScienceData/blob/master/inst/extdata/appeears/MCD12Q1.051_aid0001.nc?raw=true"
lst_url="https://github.com/adammwilson/DataScienceData/blob/master/inst/extdata/appeears/MOD11A2.006_aid0001.nc?raw=true"

download.file(lulc_url,destfile="data/MCD12Q1.051_aid0001.nc", mode="wb")
download.file(lst_url,destfile="data/MOD11A2.006_aid0001.nc", mode="wb")

lulc=rast("data/MCD12Q1.051_aid0001.nc",subds="Land_Cover_Type_1")
lst=rast("data/MOD11A2.006_aid0001.nc",subds="LST_Day_1km")

lulc=lulc[[13]]
plot(lulc)

  Land_Cover_Type_1 = c(
    Water = 0, 
    `Evergreen Needleleaf forest` = 1, 
    `Evergreen Broadleaf forest` = 2,
    `Deciduous Needleleaf forest` = 3, 
    `Deciduous Broadleaf forest` = 4,
    `Mixed forest` = 5, 
    `Closed shrublands` = 6,
    `Open shrublands` = 7,
    `Woody savannas` = 8, 
    Savannas = 9,
    Grasslands = 10,
    `Permanent wetlands` = 11, 
    Croplands = 12,
    `Urban & built-up` = 13,
    `Cropland/Natural vegetation mosaic` = 14, 
    `Snow & ice` = 15,
    `Barren/Sparsely vegetated` = 16, 
    Unclassified = 254,
    NoDataFill = 255)

lcd=data.frame(
  ID=Land_Cover_Type_1,
  landcover=names(Land_Cover_Type_1),
  col=c("#000080","#008000","#00FF00", "#99CC00","#99FF99", "#339966", "#993366", "#FFCC99", 
        "#CCFFCC", "#FFCC00", "#FF9900", "#006699", "#FFFF00", "#FF0000", "#999966", "#FFFFFF", 
        "#808080", "#000000", "#000000"),
  stringsAsFactors = F)
# colors from https://lpdaac.usgs.gov/about/news_archive/modisterra_land_cover_types_yearly_l3_global_005deg_cmg_mod12c1
kable(head(lcd))

# convert to raster (easy)
lulc=as.factor(lulc)

# update the RAT with a left join
levels(lulc)=left_join(levels(lulc)[[1]],lcd)[-1,]
activeCat(lulc)=1

# plot it
gplot(lulc)+
  geom_raster(aes(fill=as.factor(value)))+
  scale_fill_manual(values=setNames(lcd$col,lcd$ID),
                    labels=lcd$landcover,
                    breaks=lcd$ID,
                    name="Landcover Type")+
  coord_equal()+
  theme(legend.position = "right")+
  guides(fill=guide_legend(ncol=1,byrow=TRUE))
  
plot(lst[[1:12]])

scoff(lst)=cbind(0.02,-273.15)
plot(lst[[1:10]]) 


#part 1! :D

#defining a new sf point (code taken from instructions)
lw= data.frame(x= -78.791547,y=43.007211) %>%   st_as_sf(coords=c("x","y"),crs=4326)

#tranforming the point to the projection of the raster
lw %>% 
  st_transform(st_crs(lulc))

#extracting the lst data for the point lw
extracted_lst <- terra::extract(lst,lw,buffer=1000,fun=mean,na.rm=T)

#transposing the lst data for the point lw ???
transposed_lst <- t(extracted_lst[-1])

#extracting the dates for each layer
dates <- time(lst)

dates_df <- data.frame(time = dates)

#combining the dates and transposed raster values into a data frame
lst_dates <- bind_cols(dates_df, transposed_lst)

#adding a column name to lst column in new data frame
names(lst_dates)[2] <- "lst"

#plotting the data
ggplot(lst_dates, aes(x = time, y = lst)) +
  geom_point() +
    geom_smooth(span = .05, color = "deep pink", size = .75) +
      labs(x = "Date", y = "Monthly Mean Land Surface Temperature (C)")
      
#part 2! :)

#summarizing the mean value per month 
lst_month <- terra::tapp(lst, index = 'month', fun = mean, na.rm = T)
names(lst_month)<-month.name[as.numeric(stringr::str_replace(names(lst_month),"m_",""))]

print(lst_month["February"])

print(lst_month[5])
#setting layer names to months (code taken from instructions)
result <- lst_month![sapply(lst_month, is.null)]

print(result)



tm_shape(lst_month) +
  tm_raster()
  
  nlyr(lst_month)
  
  plot(lst_month["February"])
  p

#plotting the map for each month 
gplot() +
  geom_tile() +
    facet_wrap(~names(lst_month))

#calculating the monthly mean for the entire image (code taken from instructions)
global(lst_month,mean,na.rm=T)

#part 3! :D

#resample lulc to lst grid 
#lulc2 <- resample(lulc, lst, method = near)

#extract values from lst_month and lulc (code taken from instructions)
lcds1=cbind.data.frame(
values(lst_month),
ID=values(lulc2[[1]]))%>%
na.omit()

#tidy the data (code taken from instructions)
gather(key='month',value='value',-Land_Cover_Type_1_13)

#convert ID to numeric
#Use mutate(ID = as.numeric(Land_Cover_Type_1_13), month = factor(month, levels = month.name, ordered = TRUE)) to convert ID to numeric (e.g. ID=as.numeric(Land_Cover_Type_1_13) and month to an ordered factor with month=factor(month,levels=month.name,ordered=T).

#filter the data
#use filter() and landcover%in%c("Urban & built-up","Deciduous Broadleaf forest")

#ggplot to illustrate monthly variability in lst between the two land cover types
#ggplot([data])+
#geom_point() +
#facet_wrap(~landcover)
